hugo:
  basePath: "/var/www/blog"
  dataDir: "data"
  contentDir: "content"
  imageDir: "static/images/books"
openLibrary:
  httpTimeout: 10
  cacheTTL: 15
  userAgent: "HugoBooks/1.0 (aczietlow@zietlow.io)"
  baseUrl: ""
